version: '3'

services:
 web:
    build: .
    command: sh -c "python3 manage.py runserver 0.0.0.0:8000"
    # Disable this mount when running in prod mode.
    volumes:
      - .:/example
    ports:
      - "8000:8000"
    restart: unless-stopped